Add Squid pre-processing test Add header

diff --git a/SquidGuard_AU b/SquidGuard_AU
--- a/SquidGuard_AU
+++ b/SquidGuard_AU
@@ -1,6 +1,7 @@
 #!/bin/bash
 # Copyright 1999-2012 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
+# $Header: https://raw.github.com/jaypeche/SquidGuarg_AU/master/SquidGuard_AU, v0.0.2 2012/06/24 16:53.23 jaypeche Exp $
 
 DESCRIPTION="This script is used to update your SquidGuard database"
 HOMEPAGE="http://www.squidguard.org"
@@ -8,33 +9,39 @@ HOMEPAGE="http://www.squidguard.org"
 SRC_URI="ftp://ftp.univ-tlse1.fr/blacklist"
 DATABASE="/etc/squidGuard/db/blacklists"
 CONFIGFILE="/etc/squidGuard/squidGuard.conf"
+SQUIDPID="/var/run/squid.pid"
 LOGFILE="/var/log/squidGuard"
 
 echo
-echo -e "\\033[1;32m* \\033[1;39m${DESCRIPTION}"
-echo -e "\\033[1;32m* \\033[1;39mLook at ${HOMEPAGE} for more information"
+echo -e "\\033[1;32m * \\033[0;39m${DESCRIPTION}"
+echo -e "\\033[1;32m * \\033[0;39mLook at \\033[1;34m${HOMEPAGE} \\033[0;39mfor more information"
 echo -e "\\033[0;39m"
 
-[[ "$EUID" != 0 ]] && echo -e "\\033[1;31m* \\033[1;39mThis script must be run as root, exiting !" && exit 1
-[[ ! -f ${CONFIGFILE} ]] && echo -e "\\033[1;31m* \\033[1;39mThe configuration file ${CONFIGFILE} does not exist !" && exit 1
+# Pre-processing tests
+[[ $EUID != 0 ]] && echo -e "\a\\033[1;31m * \\033[1;39mWARNING: \\033[0;39mThis script must be run as root, exiting !" && exit 1
+[[ ! -f ${CONFIGFILE} ]] && echo -e "\a\\033[1;31m * \\033[1;39mWARNING: \\033[0;39mThe configuration file ${CONFIGFILE} does not exist !" && exit 1
+[[ ! -e ${SQUIDPID} ]] && echo -e "\a\\033[1;31m * \\033[1;39mWARNING: \\033[0;39mSquid is not running !" && exit 1
 
-for base in $(cat ${CONFIGFILE} | grep ^dest | awk '{print $2}' | sort -d)
+for base in $(cat ${CONFIGFILE} | grep ^dest | awk '{print $2}' | sort -d) # Parse squidGuard config file
 do
-   echo "Downloading base ${base}..."
+   echo "Downloading base ${base} ..."
    cd /tmp
    wget --continue --quiet --timeout=30 ${SRC_URI}/${base}.tar.gz
    if [ ! -e ${base}.tar.gz ]; then
-        echo -e "\\033[1;31m* \\033[1;39mBase ${base} not found, please make your checks !" && exit 1
+	echo
+   	echo -e "\a\\033[1;31m * \\033[1;39mWARNING: \\033[0;39mThe base \"${base}\" was not found on this server ..."
+	echo "            Please make your checks !"
+	exit 1
    fi
    tar -xvzf ${base}.tar.gz -C ${DATABASE}
    rm /tmp/${base}.tar.gz
    echo
 done
 
-echo "Generating database.. This could take a while, please wait..."
+echo "Generating database ... This could take a while, please wait ..."
 /usr/bin/squidGuard -C all || exit 1
 
-echo "Checking permissions..."
+echo "Checking permissions ..."
 chown -R squid:squid ${DATABASE} ${LOGFILE}
 
 /etc/init.d/squid reload
